INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_CLIENT');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO roles(name) VALUES('ROLE_RECEPTIONIST');
INSERT INTO roles(name) VALUES('ROLE_KITCHEN');
INSERT INTO roles(name) VALUES('ROLE_CLEANING');